# Generated by Django 4.0.5 on 2022-06-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100, null=True)),
                ('filtrada', models.BooleanField(default=False)),
                ('slug', models.SlugField(default='')),
            ],
        ),
    ]
